env:
  NIXPKGS_ALLOW_UNFREE: "1"
  NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz"

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest  
    name: Build für amd64/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
        # Setup hardware emulator using QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Enable Nix Flakes
      - name: Enable Nix Flakes
        run: |
          echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
          systemctl restart nix-daemon

      # Build for ARM64
      - name: Build for ARM64
        run: nix build --experimental-features 'nix-command flakes' nixpkgs#pkgsCross.aarch64-linux

      # Build for Windows
      - name: Build for Windows
        run: nix build --experimental-features 'nix-command flakes' nixpkgs#pkgsCross.x86_64-windows
